# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'MotorHelper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #for xml analysis
  pod 'Alamofire'
  pod 'SWXMLHash'
  pod 'AEXML'
  pod 'StringExtensionHTML'
  #for firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  #for keyboard
  pod 'IQKeyboardManagerSwift'
  #for rating
  pod 'Cosmos', '~> 8.0'
  # Pods for MotorHelper

end
